# Generated by Django 4.2 on 2025-04-21 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên thẻ/ví')),
                ('card_type', models.CharField(choices=[('credit', 'Thẻ tín dụng'), ('debit', 'Thẻ ghi nợ'), ('ewallet', 'Ví điện tử'), ('cash', 'Tiền mặt'), ('other', 'Khác')], max_length=10, verbose_name='Loại thẻ/ví')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Số dư')),
                ('card_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='Số thẻ')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Ngày hết hạn')),
                ('color', models.CharField(default='#007bff', max_length=20, verbose_name='Màu sắc')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Thẻ/Ví',
                'verbose_name_plural': 'Thẻ/Ví',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên danh mục')),
                ('type', models.CharField(choices=[('income', 'Thu nhập'), ('expense', 'Chi tiêu')], max_length=10, verbose_name='Loại danh mục')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Icon')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Danh mục',
                'verbose_name_plural': 'Danh mục',
                'ordering': ['type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Số tiền')),
                ('transaction_type', models.CharField(choices=[('income', 'Thu nhập'), ('expense', 'Chi tiêu'), ('transfer', 'Chuyển khoản')], max_length=10, verbose_name='Loại giao dịch')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Ngày giao dịch')),
                ('time', models.TimeField(default=django.utils.timezone.now, verbose_name='Thời gian giao dịch')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('image', models.ImageField(blank=True, null=True, upload_to='transactions/', verbose_name='Hình ảnh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance_app.card', verbose_name='Thẻ/Ví')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance_app.category', verbose_name='Danh mục')),
                ('to_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transfers', to='finance_app.card', verbose_name='Đến thẻ/ví')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Giao dịch',
                'verbose_name_plural': 'Giao dịch',
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên mục tiêu')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Số tiền mục tiêu')),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Số tiền hiện tại')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(verbose_name='Ngày kết thúc')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('status', models.CharField(choices=[('in_progress', 'Đang thực hiện'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy')], default='in_progress', max_length=15, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Mục tiêu',
                'verbose_name_plural': 'Mục tiêu',
                'ordering': ['-end_date'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Số tiền')),
                ('period', models.CharField(choices=[('daily', 'Hàng ngày'), ('weekly', 'Hàng tuần'), ('monthly', 'Hàng tháng'), ('yearly', 'Hàng năm')], default='monthly', max_length=10, verbose_name='Chu kỳ')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='finance_app.category', verbose_name='Danh mục')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Ngân sách',
                'verbose_name_plural': 'Ngân sách',
                'ordering': ['-start_date'],
            },
        ),
    ]
