# Generated by Django 5.2 on 2025-04-21 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0002_category_is_default_alter_category_unique_together'),
        ('finance_app', '0004_add_default_categories'),
    ]

    operations = [
    ]
