# Generated by Django 4.2.10 on 2025-05-15 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0009_add_updated_at_to_transaction'),
        ('finance_app', '0012_alter_card_card_type'),
    ]

    operations = [
    ]
